### PR TITLE
cytosim dimensionality reduction script

### PR DESCRIPTION
**Pull request by youmustfight**
Exported the notebook created in https://github.com/simularium/subcell-analysis/pull/9 to a python script, and then re-wrote it to handle multiple dataset inputs, only do analysis on individual simulations, allow analysis to align fibers or not, and incorporate color distinctions of time, fibers, and simulations. See more below!

### CODE REVIEW

**Comment by youmustfight** [comment]
Re-writing the plotting code but keeping this for reference as to what it should look like

image

**Comment by youmustfight** [comment]
For the sake of reference, adding the charts generated in the prior commit below

| PAC | PaCMAP | PaCMAP (Aligned) |
| --- | --- | --- |
| output10 | output11 | output12 |
| output7 | output8 | output9 |
| output1 | output2 | output3 |
| output4 | output5 | output6 |

**Comment by youmustfight** [comment]
Simulation of ReaDDy fibers (aka repeats) is working

| Pac | PaCMAP | PaCMAP (Aligned) |
| --- | --- | --- |
| image | image |
| image | image |
| image | image |
| image | image |

**Comment by youmustfight** [comment]
Reworked data loading and added cytosim. Plotting loop now across velocities/simulations. Future step is to do overlapped embeddings, but the variables between simulations (monomer counts, timepoints) change a lot.

| | Microscopy (nvm I think this is Cytosim subsample?)  | ReaDDY | Cytosim |
| --- | --- | --- | --- |
| PCA | image | image | image | 
| PCA (Aligned) | image | image | image |
| PaCMAP | image | image | image |
| PaCMAP (Aligned) | image | image | image |

**Comment by youmustfight** [comment]
Not to self, when I run cytosim at velocities other than 4.7, I need to fix this error:
`ValueError: cannot reshape array of size 1510515 into shape (31690,1503)` for 15, 150
`ValueError: cannot reshape array of size 4756995 into shape (31690,1503)` for 47

**Comment by mattakamatsu** [comment]
Our hope is to take text files like these - XYZ coordinates of filaments from tomograms, in nm - and add them to the existing PCA plot. The goal will be to see where these filaments lie, in PCA space, compared to the existing PCA plot of cytosim + readdy (when they are on the same plot).
[UnbranchedActin_TomoAugust_27_earlyCME.txt](https://github.com/simularium/subcell-analysis/files/13732776/UnbranchedActin_TomoAugust_27_earlyCME.txt)
We would want to sample (subsample or interpolate) so that each has a defined distance between model points (and then we'll look at PCA space accordingly to try to account for effects based on the number of model points per filament)

**Pull request merged**
